
dataset:
  root_dir: Dataset/FGNET
  images_dir: Dataset/FGNET/images
  labels_csv: Dataset/FGNET/labels.csv
  img_size: 224
  train_split: 0.7
  val_split: 0.1
  split_strategies: ["random", "identity"]

training:
  batch_size: [16, 32]
  epochs: [20, 40, 60]
  learning_rate: [0.0001, 0.0005, 0.00001]
  loss: mse
  patience: 5

models:
  names:
    - resnet18
    - resnet34
    - resnet50
    - mobilenet
    - efficientnet

mlflow:
  experiment_name: Age_Prediction_Full_Comparison
  model_dir: saved_models


